###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: cyberback-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: .
      container_name: cyberback-php-fpm
      working_dir: /application
      environment:
        - "MAP_ASSETS_DIR=/application/assets/maps/"
        - "APP_ENV=prod"
        - "DATABASE_URL=sqlite:////tmp/data.db"
        - "PUSHER_APP_ID=1"
        - "PUSHER_KEY=2"
        - "PUSHER_SECRET=3"
        - "PUSHER_APP_CLUSTER=us2"
      volumes:
        - .:/application
        - /tmp/data.db:/tmp/data.db

