index:
    path: /
    controller: App\Controller\DefaultController::index


createGame:
    path: /game
    controller: App\Controller\LobbyController::createGame
    methods: [POST]
getGame:
    path: /game/{gameId}
    controller: App\Controller\LobbyController::getGame
    methods: [GET]
addPlayer:
    path: /player
    controller: App\Controller\LobbyController::createPlayer
    methods: [POST]


getUnits:
    path: /units/{gameId}
    controller: App\Controller\GameController::getUnits
    methods: [GET]
getUnit:
    path: /unit/{unitId}
    controller: App\Controller\GameController::getUnit
    methods: [GET]

startTurn:
    path: /turns
    controller: App\Controller\TurnController::createTurn
    methods: [POST]
updateTurn:
    path: /turns/{turnId}
    controller: App\Controller\TurnController::updateTurn
    methods: [PATCH]
createUnitAction:
    path: /unitAction
    controller: App\Controller\TurnController::createUnitAction
    methods: [POST]
